/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


case class ChatCompletionRequestMessage(
  /* The role of the author of this message. */
  role: ChatCompletionRequestMessageEnums.Role,
  /* The contents of the message */
  content: String,
  /* The name of the user in a multi-user chat */
  name: Option[String] = None
)

object ChatCompletionRequestMessageEnums {

  type Role = Role.Value
  object Role extends Enumeration {
    val System = Value("system")
    val User = Value("user")
    val Assistant = Value("assistant")
  }

}
