/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


case class CreateAnswerResponse(
  `object`: Option[String] = None,
  model: Option[String] = None,
  searchModel: Option[String] = None,
  completion: Option[String] = None,
  answers: Option[Seq[String]] = None,
  selectedDocuments: Option[Seq[CreateAnswerResponseSelectedDocumentsInner]] = None
)

