/**
 * OpenAI API
 * APIs for sampling from and fine-tuning language models
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


case class CreateSearchRequest(
  /* Query to search against the documents. */
  query: String,
  /* Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both.  */
  documents: Option[Seq[String]] = None,
  /* The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both.  */
  file: Option[String] = None,
  /* The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set.  */
  maxRerank: Option[Int] = None,
  /* A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set.  */
  returnMetadata: Option[Boolean] = None,
  /* A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).  */
  user: Option[String] = None
)

